[workspace]
authors = ["Ivan S Gill <ivan_gill@sfu.ca>"]
channels = ["conda-forge"]
name = "amr-tv"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
#compile = {cmd = "cd adaptagrams/cola && ./autogen.sh && ./buildPythonSWIG.sh", clean-env = true}
app = "python app.py"

[tasks.compile]
cmd = "cd adaptagrams/cola && ./autogen.sh && ./buildPythonSWIG.sh"
env = {CC = "clang", CXX = "clang++" }

[dependencies]
automake = ">=1.17,<2"
cairo = ">=1.18.4,<2"
libtool = ">=2.5.4,<3"
pkg-config = ">=0.29.2,<0.30"
python = ">=3.9.0,<3.10"
make = ">=4.4.1,<5"
binutils = ">=2.44,<3"
clang = ">=20.1.7,<21"
clangxx = ">=20.1.7,<21"

[pypi-dependencies]
setuptools = ">=80.9.0, <81"
dash = "==1.20.0"
dash-bootstrap-components = "==0.12.2"
networkx = "==2.8.5"
Werkzeug = "==2.0.0"
numpy = "==1.23.4"
pandas = "==1.5.1"
gunicorn = "==23.0.0"
swig = "==4.2.1"
