# Generated by Django 3.1.2 on 2020-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('organism_group', models.TextField()),
                ('isolate', models.TextField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('isolation_source', models.TextField()),
                ('host', models.TextField()),
                ('amr_genotypes', models.JSONField()),
            ],
        ),
    ]
