# Generated by Django 3.1.2 on 2020-11-13 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMRGenotype',
            fields=[
                ('amr_genotype', models.TextField(primary_key=True, serialize=False)),
                ('isolates', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
