# Generated by Django 3.1.2 on 2020-11-12 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('organism_group', models.TextField()),
                ('isolate', models.TextField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('location', models.TextField()),
                ('isolation_source', models.TextField()),
                ('host', models.TextField()),
                ('amr_genotypes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
