# Generated by Django 3.1.2 on 2020-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isolate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolateGenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate', models.TextField()),
                ('amr_genotype', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('organism_group', models.TextField()),
            ],
        ),
    ]
