name: Cross-platform build test
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest-large, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi install --manifest-path pyproject.toml
      - run: pixi compile --manifest-path pyproject.toml
