name: Cross-platform build test
on: workflow_dispatch

#on:
#  pull_request:
#    branches:
#      - development
#  workflow_dispatch:

jobs:
  #  build:
  #    strategy:
  #      matrix:
  #        os: [ubuntu-latest, macos-latest-large, macos-latest]
  #        os: [ubuntu-latest]
  #    runs-on: ${{ matrix.os }}
  test-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - run: apt-get update && apt-get install -y git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run compile
      - run: |
          # pixi run start with timeout
          set +e
          timeout 10s pixi run start
          status=$?
          set -e
          if [ $status -eq 124 ]; then
            echo "Timeout reached (normal)"
            exit 0
          elif [ $status -ne 0 ]; then
            echo "App crashed with status $status"
            exit $status
          fi
      - name: Archive start.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: start-ubuntu-latest.log
          path: start.log
  test-macos:
    strategy:
      matrix:
        os: [
          # Intel
          macos-13,
          # arm64
          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run compile
      - run: |
          # pixi run start with timeout
          set +e
          # macos does not have timeout but coreutils does
          pixi run timeout 10s pixi run start > start.log 2>&1
          status=$?
          set -e
          if [ $status -eq 124 ]; then
            echo "Timeout reached (normal)"
            exit 0
          elif [ $status -ne 0 ]; then
            echo "App crashed with status $status"
            exit $status
          fi
      - name: Archive start.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: start-${{ matrix.os }}.log
          path: start.log
